"""Profile

Revision ID: f38f79d4b7d1
Revises: bb1f5e515779
Create Date: 2018-09-15 16:09:31.604206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f38f79d4b7d1'
down_revision = 'bb1f5e515779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_comment_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'comment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_comment_id_fkey', 'users', 'comments', ['comment_id'], ['id'])
    # ### end Alembic commands ###
